// The built-in scenario prompt bank.  A game shuffles a copy of this list and draws from
// it without repeats until it is exhausted (then reshuffles).  Host-typed custom prompts
// are a deferred feature (see DESIGN.md cut-lines).
export const MIXTAPE_PROMPTS: string[] = [
  "Best song for a 2am road trip",
  "The song that should play when you walk into the room",
  "Best song to cook dinner to",
  "The ultimate pump-up song before a big moment",
  "Best song to cry in the shower to",
  "The song that always gets the whole party dancing",
  "Best song for a slow Sunday morning",
  "The perfect song for a first-date montage",
  "Best song to blast with the windows down",
  "The song you'd want playing during the closing credits of your life",
  "Best song to fall asleep to",
  "The most underrated song of all time",
  "Best song to hype up a workout",
  "The song that instantly takes you back to being a kid",
  "Best song for a rainy day by the window",
  "The perfect song to end a wedding on",
  "Best song to sing badly at karaoke",
  "The song that should be the national anthem of summer",
  "Best song for a dramatic slow-motion entrance",
  "The song you'd play to impress someone you just met",
  "Best song to study or focus to",
  "The most romantic song ever written",
  "Best song for a campfire singalong",
  "The song that gets stuck in your head for days",
  "Best song to break a bad mood",
  "The perfect villain theme song",
  "Best song for a long-distance goodbye",
  "The song that deserves to be way more famous",
  "Best song to dance with your grandparents to",
  "The ultimate 'main character walking through the city' song",
  "Best song for a beach bonfire at sunset",
  "The song you'd want to hear at your victory parade",
  "Best song to clean the whole house to",
  "The perfect song for a heartbreak recovery playlist",
  "Best song to introduce someone to your favorite genre",
  "The song that feels like a warm hug",
  "Best song for a New Year's Eve countdown",
  "The most dramatic key change in music history",
  "Best song to blast to annoy your neighbors",
  "The song you'd pick to represent your whole personality",
];
